### ISSUE TITLE
How to get this working?

### ISSUE THREAD

**Issue by krishnakanthpps** [MVHSIgnition/mvlecture#2]
Can you help me in getting this working? Any steps to setup?

**Comment by jacobismael** [comment]
If you download the files and then install all the node modules, all you have to do is run ```node server.js``` and go to localhost:1266

**Comment by erikbZhang** [comment]
We're working on a readme with instructions right now!

**Comment by arjunpat** [comment]
Hey! We just added a readme file. Let us know if you have any questions or concerns!
